
language: java

install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: "bundle exec rake && RAILS_ENV=production bundle exec rake assets:precompile:primary"
